__title__ = 'sellsy_api'
__description__ = 'sellsy_api is a tiny client for Sellsy API'
__url__ = 'https://github.com/Annouar/sellsy-api'
__version__ = '0.0.1'
__author__ = 'Annouar'
__license__ = 'MIT'
